# -*- coding: utf-8 -*-
"""Textblob.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15kn8SFpjunSLDFAYkRDXtdjj8vWhPKN1
"""

!pip install textblob

from textblob import TextBlob

def convert_word(string):
  alphabets = string.split()
  alphabet_list =list(alphabets)
  return alphabet_list

print(convert_word("Hello"))

inp = input("Please enter a word :")
word = convert_word(inp)
corrected_word =[]
correct_word =[]

for i in word:
  corrected_word.append(TextBlob(i))

print(f"Wrong word :",inp)

for i in corrected_word:
  print(f"The right word is :",i.correct(),end="")

